### ISSUE TITLE
ExecuteScriptMarkLogic should route to FAILURE on error

### ISSUE THREAD

**Issue by dmcassel** [marklogic/nifi#125]
When something goes wrong in an ExecuteScriptMarkLogic processor, it just calls `logErrorAndRollbackSession`. The flow file remains in the queue and is retried after a penalty period. Because there's no way to route to the FAILURE relationship, there's no way to build the flow to notify someone about the error -- it just keeps trying the same thing over and over. 

I'd like to see errors routed to FAILURE. I think this is as simple [as changing this](https://github.com/marklogic/nifi/blob/master/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/ExecuteScriptMarkLogic.java#L304):

```
        } catch (final Throwable t) {
            this.logErrorAndRollbackSession(t, session);
        }
```

to this:

```
        } catch (final Throwable t) {
            session.transfer(originalFF , FAILURE)
        }
```

and moving the declaration of `originalFF` outside of the `try`:

```
        FlowFile originalFF = nulll;
        try {
            originalFF = session.get();
            if (originalFF == null) {
                return;
            }
```

**Comment by dmcassel** [comment]
Even better -- create a new `ERROR` relationship. If the code throws an error, route the flow file to error. Other problems (such as network interruptions) can continue to go to the `FAILURE` relationship. This way we can do retries on failures, but alert on errors.

**Comment by rjrudin** [comment]
@dmcassel I'm wondering about catching `FailuredRequestException` and treating that as an "error" and everything else as a "failure". I did some testing of various errors:

1. A bad script produces an FRE
2. An invalid username/password produces an FRE
3. A bad host or bad port produces a MarkLogicIOException
4. Basic auth instead of digest auth produces an FRE

So an FRE captures both script errors and authentication errors. So that wouldn't meet your goal of "if the code throws an error".

What would do the trick is to call `checkConnection` on the `DatabaseClient` before proceeding. If that fails, we can route the FlowFile to an e.g. "connection failed" relationship. If that succeeds, we execute the script and if that fails, we route the FlowFile to a "failure" relationship. 

If that sounds good, I'd rather do that as a separate ticket and apply that across all the processors. I'm not sure yet that we should do it though, because various connection failures can differ in whether a retry is going to matter - i.e. a failed password is unlikely to change on a retry, but an IO exception due to the host being temporarily unavailable may succeed on a retry. Adding new relationships also has the downside of requiring users to configure those relationships on an upgrade, regardless of whether they care about them or not. 

In any event, for the scope of this ticket, I just want to fix the original issue and have it behave like `ExtensionCallML` - i.e. route the failed FlowFile to the "Failure" relationship so it can be addressed there. It will have the error message in it, so worst case, you could apply logic to determine whether to route it back for retry.
