### ISSUE TITLE
ExtensionCallMarklogic Post method not propagating body

### ISSUE THREAD

**Issue by Acidstuff** [marklogic/nifi#57]
The ExtensionCallMarklogic processor (1.8.0.3) **post** method doesn't propagate the flowfile content, a simple few nodes XML in Dutch, to a dedicated custom API extension. 

![2019-02-12_17h28_42](https://user-images.githubusercontent.com/887144/52650998-ac096580-2eeb-11e9-9d9d-d18e3899e240.png)

Flowfile is waiting in the queue, contents verified by peeking the list queue. API extension code is hit but the XML document payload is empty and will return a custom error and the processor task will fail. 

Did a Wireshark trace and body is not transferred. Did the same action by using Postman (and Wireshark) and the document arrives in the API extension and will be processed.

![2019-02-12_17h23_09](https://user-images.githubusercontent.com/887144/52650638-ede5dc00-2eea-11e9-88b1-cba77c61ebb0.png)

![2019-02-12_17h07_04](https://user-images.githubusercontent.com/887144/52650580-cdb61d00-2eea-11e9-909f-070d31d7c842.png)

**Comment by rjrudin** [comment]
I am wondering if the improper Extension Name is the issue here; the extension name should only be "documents", and then the parameters - e.g. input-flow - should be passed along via "param:input-flow" properties on the processor.

We have tests verifying that a POST to a custom REST extension both receives the input from a FlowFile and returns the output correctly. I did a manual test to verify that as well. 

What seems odd to me is that the output of the REST extension is being appended instead of written to the FlowFile, but that's a separate matter I'm looking into. 

Closing this, but if you are able to reproduce with the 1.9.1.5 release (though I don't think the 1.8.0.3 release has the problem either), please create a new ticket with steps to reproduce.
