### ISSUE TITLE
Failed to properly Initialize Processor due to java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by harshanandigama** [marklogic/nifi#69]
I have multiple PutMarklogic 1.8.0.3 processors and only one processor at once is coming up and the remaining 4 are having the error Failed to properly Initialize Processor due to java.lang.reflect.InvocationTargetException. when I disable and enable the DatabaseClientService the error free processor is shifting but at any given point of time I am having 4 out of 5 processors with errors.

**Comment by gvaidees** [comment]
Would you be able to export your flow template and attach that to the issue? Thanks.

**Comment by harshanandigama** [comment]
I have updated my flow to use invoke http instead of multiple Putmarklogic processors. But even if I have a single processor I am getting the same issue. I have issues uploading the template even after zipping the file. Please see the attached screenshot
![template](https://user-images.githubusercontent.com/50381688/57699903-d5d74300-7626-11e9-94c9-5d9f7a235bdf.png)

**Comment by rjrudin** [comment]
I tried to reproduce this by doing the following:

1. Added a controller service to write to the Documents DB
2. Added two GenerateFlowFile processors that each run every 2 or 3 seconds
3. Added a PutMarkLogic processor, 1 connected to each GenerateFlowFile processor, to write the generated flow files
4. Started up all processors

The test shows both PML processors writing correctly, with both referring to the Documents database controller service. 

I am wondering if the "failure to initialize" wasn't about having multiple PML processors using the same controller service but rather some other bug that is now fixed in the 1.9.1.5 release. 

If you can reproduce this once 1.9.1.5 is released, please open a new ticket with steps on how to reproduce.
