### ISSUE TITLE
Results from ExecuteScriptMarklogic shows incorrect properties.

### ISSUE THREAD

**Issue by ranvirsingh** [marklogic/nifi#72]
I fetched few records from QueryMarklogic and then inserted those flowfiles into ExecuteScriptMarkLogic, the output in results queue exhibits same properties as of input files.
nar version 1.8.0.3

**Comment by rjrudin** [comment]
The design of ExecuteScriptML is that for each value returned by the call to ML, a new FlowFile is created which is based on the original FlowFile. Thus, the new FlowFile will have all the same properties, but a different uuid. 

I did a test of this, and here's what the FF looked like before the processor was called:

```
---------------------ORIGINAL---------------------
Standard FlowFile Attributes
Key: 'entryDate'
	Value: 'Mon Jan 25 17:06:23 EST 2021'
Key: 'lineageStartDate'
	Value: 'Mon Jan 25 17:06:23 EST 2021'
Key: 'fileSize'
	Value: '10'
FlowFile Attribute Map Content
Key: 'filename'
	Value: '56f099f8-a8ea-4d7f-86b5-3b8848111190'
Key: 'path'
	Value: './'
Key: 'uuid'
	Value: '56f099f8-a8ea-4d7f-86b5-3b8848111190'
---------------------ORIGINAL---------------------
```

And here's what it looked like after the processor was called:

```
----------------------AFTER-----------------------
Standard FlowFile Attributes
Key: 'entryDate'
	Value: 'Mon Jan 25 17:06:23 EST 2021'
Key: 'lineageStartDate'
	Value: 'Mon Jan 25 17:06:23 EST 2021'
Key: 'fileSize'
	Value: '21'
FlowFile Attribute Map Content
Key: 'filename'
	Value: '56f099f8-a8ea-4d7f-86b5-3b8848111190'
Key: 'path'
	Value: './'
Key: 'uuid'
	Value: '21607b68-5987-477f-9927-422c7570aa43'
----------------------AFTER-----------------------
```

Note that the "after" FF has a new uuid, but "filename" still refers back to the incoming FF. 

So I believe this is working as designed and not a bug, but I can see an argument that the processor should create brand new FlowFiles instead of creating ones based on the incoming one. That would be a new ticket describing the need for this feature - it could easily be a new configuration option on the processor that allows for brand new flowfiles to be created.
