### ISSUE TITLE
Change the Expression language scope for the PutMarklogicProcessor

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic/nifi#87]
Can we change the scope of the dynamic variables in Put Marklogic processor from ` ExpressionLanguageScope.VARIABLE_REGISTRY` to ` ExpressionLanguageScope.FLOWFILE_ATTRIBUTE`.

As we have flow files coming from various sources and each one can have different `trans:` attributes.. it would be nice if we can change the scope to FLOWFILE_ATTRIBUTE so that we can use same processor.

**Comment by rjrudin** [comment]
I don't think we can do this efficiently. That's because the transform object is created before any FlowFiles arrive, and only one is created. In order to support FlowFile-level properties, the processor would have to create a new WriteBatcher with a new ServerTransform for every FlowFile, and that would significantly impact performance.
